/*
-- Query: SELECT * FROM mydb.cgenero
LIMIT 0, 10

-- Date: 2022-11-24 10:37
*/
INSERT INTO `CGENERO` (`CGE_PK_GENERO`,`CGE_NOMBRE`) VALUES (1,'FEMENINO');
INSERT INTO `CGENERO` (`CGE_PK_GENERO`,`CGE_NOMBRE`) VALUES (2,'MASCULINO');
